### ISSUE TITLE
Crash with OBS 28.0.0-beta1

### ISSUE THREAD

**Issue by VennStone** [ratwithacompiler/OBS-captions-plugin#94]
I was playing around with the OBS 28 beta this afternoon. It fails to launch with the captions plugin installed. I don't know if the move to QT6 is the cause? This is on Debian 11. Plugin works great on OBS v27. 

Thought I would give it a mention. 

```
CaptionPluginSettings
enabled: 0
SourceCaptionerSettings
  streaming_output_enabled: 1
  recording_output_enabled: 0
  Scene Collection Settings:
    CaptionSourceSettings
      caption_source_name: 
      mute_when: 0
      mute_source_name: 
    TextOutputSettings
      enabled: 0
      text_source_name: 
      line_length: 60
      line_count: 4
      capitalization: 0
  ContinuousCaptionStreamSettings
    connect_second_after_secs: 280
    switchover_second_after_secs: 282
    minimum_reconnect_interval_secs: 10
    CaptionStreamSettings
      connect_timeout_ms: 5000
      send_timeout_ms: 5000
      recv_timeout_ms: 180000
      max_queue_depth: 50
      download_thread_start_delay_ms: 40
  CaptionFormatSettings
    caption_line_length: 32
    caption_line_count: 3
    capitalization: 0
    caption_insert_newlines: 0
    user_replacements: 0
  TranscriptSettings
    enabled: 0
    output_path: 
    format: srt
    recording_filename_type: recording
    recording_filename_custom: 
    recording_filename_exists: append
    streaming_filename_type: datetime
    streaming_filename_custom: 
    streaming_filename_exists: append
    srt_target_duration_secs: 8
    srt_target_line_length: 44
    streaming_transcripts_enabled: 0
    recording_transcripts_enabled: 0
QObject::startTimer: Timers can only be used with threads started with QThread
QWidget: Must construct a QApplication before a QWidget
Aborted
```
